<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include 'layout/head.phtml'; ?>
    </head>
    <div id="loading-page-container">
        <div class="icons-container" id="icons-container">
            <div class="icons-content">
                <i class="fa-solid fa-gear"></i>
                <i class="fa-solid fa-gear"></i>
                <i class="fa-solid fa-gear"></i>
            </div>
            <p class="color-blue">
                <span>L</span>
                <span>o</span>
                <span>a</span>
                <span>d</span>
                <span>i</span>
                <span>n</span>
                <span>g</span>
                <span>.</span>
                <span>.</span>
                <span>.</span>
            </p>
        </div>
    </div>
    <body>
        <header class="hide">
            <?php include 'layout/header-projects.phtml'; ?>
        </header>
        <div class="contact-aside hide">
        <a href="tel:0666179121">
            <i class="fa-solid fa-phone"></i>
        </a>
        <a href="mailto:jzanetti1@outlook.fr">
            <i class="fa-solid fa-envelope"></i>
        </a>
        <a href="https://www.linkedin.com/in/jordan-zanetti-044ab2174/" target="_blank">
            <i class="fa-brands fa-linkedin-in"></i>
        </a>           
    </div>
        <div class="back-to-top hide">
            <a href="#top-page">
                <i class="fa-solid fa-arrow-up"></i>
            </a>
        </div>
        <main class="projects-page hide">
            <section class="projects-container" id="projects-section">
                <div class="container">
                    <div class="row reveal">
                        <div class="col-md-12">
                            <h2>Mes <span class="underline color-blue">projets</span></h2>
                            <nav id="nav-projects-container">
                                <ul>
                                    <li>
                                        <a class="active" id="nav-btn-all" href="">Tous</a>
                                    </li>
                                    <li>
                                        <a id="nav-btn-pro" href="">Professionnel</a>
                                    </li>
                                    <li>
                                        <a id="nav-btn-perso" href="">Personnel</a>
                                    </li>
                                    <li>
                                        <a id="nav-btn-forma" href="">Formation</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div id="projects-container" class="row active">

                    </div>
                </div>
            </section>
        </main>
        <footer class="hide">
            <?php include 'layout/footer.phtml'; ?>
        </footer>
    <script type="text/javascript" src="scripts/main.js"></script>
    <script type="text/javascript" src="scripts/projects.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>