        <meta charset="UTF-8">
        <title>CV - Développeur intégrateur web</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Dévouvrez mon CV en ligne de Développeur intégrateur web - Zanetti Jordan">
        <meta name="keywords" content="Développeur web, Curriculum Vitae, HTML5, CSS3, Sass, JavaScript, WordPress, Prestashop, Photoshop, Adobe XD, Développeur Front-End, Intégration web, ">
        <meta name="author" content="Zanetti Jordan">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />        
        <link rel="stylesheet" type="text/css" href="/styles/bsmain.css">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <meta property="og:title" content="ZANETTI Jordan - Développeur Intégrateur web" />
        <meta property="og:type" content="Preview" />
        <meta property="og:url" content="https://jordanzanetti.fr/" />
        <meta property="og:image" content="https://jordanzanetti.fr/share.jpg" />
        <meta property="og:image:alt" content="Online CV - Zanetti Jordan " />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />