<div class="container-fluid bg-header">
    <div class="container">
        <div class="row">
                <div class="col-md-12 menu">
                    <nav>
                        <ul>
                            <li><a href="index.php">Accueil</a></li>
                            <li><a href="projects.phtml">Projets</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
    </div>
</div>