<div id="top-page"></div>
<div class="container-fluid bg-header">
    <div class="container">
        <div class="row">
                <div class="col-md-12 menu">
                    <nav>
                        <ul>
                            <li><a id="home-link" class="active" href="http://jordanzanetti.fr/index.php">Accueil</a></li>
                            <li><a id="projects-link" href="projects.phtml">Projets</a></li>
                        </ul>
                    </nav>
                </div>
        </div>
        </div>
        <div class="infos-container">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 header-infos">
                        <h1>
                            <span class="small-title">Zanetti <span class="color-blue">Jordan </span></span>
                            </br>
                            Développeur intégrateur <span class="color-blue">web</span>
                        </h1>
                        <a class="btn" href="#projects-section">Mes projets <i class="fa-solid fa-arrow-down"></i></a>
                    </div>
            </div>
            <div class="row all-icons-container">
                <div class="col-lg-12">
                    <div class="icons-container">
                    <div class="col-lg-3">
                        <i class="fa-solid fa-code"></i>
                        <h3>Front-end</h3>
                    </div>
                    <div class="col-lg-3">
                        <i class="fa-brands fa-wordpress-simple"></i>
                        <h3>CMS</h3>
                    </div>
                    <div class="col-lg-3">
                    <i class="fa-solid fa-mobile-screen-button"></i>
                        <h3>Responsive</h3>
                    </div>
                    <div class="col-lg-3">
                        <i class="fa-solid fa-screwdriver-wrench"></i>
                        <h3>Pack Adobe</h3>
                    </div>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>