<!DOCTYPE html>
<html lang="fr">
    <head>
        <?php include 'head.phtml'; ?>
    </head>
    <body>
        <header>
            <?php include 'header.phtml'; ?>
        </header>
        <div class="back-to-top">
            <a href="#top-page">
                <i class="fa-solid fa-arrow-up"></i>
            </a>
        </div>
        <main>
            <section class="projects-container">

            </section>
        </main>
    </body>
</html>