<!DOCTYPE html>
<html lang = "fr">
    <head>
        <?php include 'layout/head.phtml' ?>
    </head>
    <body>
        <header>
            <?php include 'layout/header.phtml' ?>
        </header>
        <div class="container">
            <div class="row">
                <div id="projects-container">

                </div>
            </div>
        </div>

        
        <script type="text/javascript" src="./scripts/projects.js"></script>
        <footer>
            <?php include 'layout/footer.phtml' ?>
        </footer>
    </body>
</html>
